repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args: ["--select", "I", "--fix"]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    name: Run MyPy typing checks.
    args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
